### ISSUE TITLE
'Point' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by hannah22w** [inkstitch/inkstitch#2592]
Hello. I keep getting the below when trying to save a PES file on Inkspace. I am just trying to re-download etc now

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'Point' object has no attribute 'geoms'

**Comment by tyrosinase** [comment]
That error is fixed in the current release, so I'm going to close the issue. You can reopen it if it persists after you've upgraded (which I assume the "re-download etc" refers to).

**Comment by hannah22w** [comment]
Still showing the same issue after I have upgraded unfortunately

**Comment by tyrosinase** [comment]
Is the error the exact same text? If not, please copy it here again. And please either zip up and post the file here, or if there are rights/confidentiality issues, upload it at https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES (I'm pretty sure that's the current drop point; if not Lex or someone will be along to correct me).

In the meantime, what's happening is that there's a stray single-point object somewhere, probably with a fill on it. You can work around it by finding that object, either by tabbing through all the objects or by doing a drag-a-rectangle select over different areas until you see an absurdly tiny one, and deleting it. The current version is supposed to be able to find all those, but it looks like it's still missing some cases.
